### ISSUE TITLE
Error Building Site

### ISSUE THREAD

**Issue by nataliepjlin** [opera7133/tella#100]
Hello! I tried both two methods on the README, but none of these work, and all showing 
`WARN 2022/03/29 23:07:14 The "twitter_simple" shortcode will soon require two named parameters: user and id. 
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.` 
I tried moving the whole file into `exampleSite`  as a theme and run it too, but sadly ended up with the same result as above. Is there any way I can fix this problem? 
Thanks a lot!!

**Comment by opera7133** [comment]
Perhaps it is because your working directory or package is under a directory containing spaces, such as `Program Files`.
You should either move the working directory or change the initial installation location of the node.js global package.

**Comment by nataliepjlin** [comment]
@opera7133 I'm not sure will directory `Natalie Lin` affect, the whole error message looks like this 

![image](https://user-images.githubusercontent.com/100992247/160814443-44b85dcc-d303-4135-82f6-4e4fa7e4dd00.png)

**Comment by opera7133** [comment]
In this case, first move the working directory to a location that does not contain spaces, then [change the global installation location of npm](https://stackoverflow.com/a/19876059).

**Comment by nataliepjlin** [comment]
@opera7133 Woah it works!!!! Thank you so much :)
