### ISSUE TITLE
Dependencies for build

### ISSUE THREAD

**Issue by rrcrrcrrc** [opera7133/tella#104]
I wanna build the site, but im have problems with it.
Which version of Hugo, Node, NPM is needed?

**Comment by opera7133** [comment]
Please provide version information for each software.
I use Node v16, NPM 8, Hugo 0.90.1 extended and it works fine.

**Comment by rrcrrcrrc** [comment]
I can deploy it on local, but when I wanna deploy it on Gitlab, I got an error. This is my gitlab-ci.yml:
```
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
```

And I got this error:

```
Start building sites … 
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended linux/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
WARN 2022/05/13 14:40:01 The "twitter_simple" shortcode will soon require two named parameters: user and id. See "/builds/rrcrrcrrc/hugoserver/content/blog/rich-content.md:25:1"
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
```

**Comment by opera7133** [comment]
Please insert `npm install` to the `script` section.
Without this, dependent packages will not be installed.

**Comment by rrcrrcrrc** [comment]
That works but I get other error that I dont know how to solve it:
```
Error: Error building site: "/builds/XXX/XXX/content/contact.md:7:1": failed to extract shortcode: template for shortcode "form" not found
```

**Comment by rrcrrcrrc** [comment]
> That works but I get other error that I dont know how to solve it:
> 
> ```
> Error: Error building site: "/builds/XXX/XXX/content/contact.md:7:1": failed to extract shortcode: template for shortcode "form" not found
> ```

It looks like there need some spaces:
```
{{ < form > }}
```
