### ISSUE TITLE
[Potential Bug] Grid objects have different sizes

### ISSUE THREAD

**Issue by UnlimitedCookies** [opera7133/tella#108]
![image](https://user-images.githubusercontent.com/49200216/180584492-23c1541c-b5d4-4116-88df-b70c31fa3c0b.png)

Flawed behavior: The containers align by the grid, but might over- or underflow, as seen in the image above.
Intended behavior: All grid objects have the same size.

**Comment by opera7133** [comment]
With 7c84dcd5b7f9c3b5d45400d581e8af1f04e5f982, so that the height becomes the maximum width. Also, each item is now centered at the top and bottom.

**Comment by UnlimitedCookies** [comment]
Awesome. Thanks for fixing this so quickly!
