### ISSUE TITLE
How to add new icons to features.json?

### ISSUE THREAD

**Issue by jonas-xyz** [opera7133/tella#109]
I want to add new icons to features.json. I tried to add some FontAwesome icons in fa6.min.css but it didn't work. Is it possible to add new ones or can you only use the ones already defined?

**Comment by opera7133** [comment]
If you want to use FontAwesome icons, enable them in `config.toml` and add the following code to `features.json`.
```json
{
    "title": "Github",
    "description": "Please fork the Github repository and contribute to this theme!",
    "icon": "fa-brands fa-github",
    "link": "https://github.com/opera7133/tella"
}
```
If you want to use something other than the default defined icons and FontAwesome icons, we recommend editing the theme or using `custom.css`.

**Comment by jonas-xyz** [comment]
Thanks a lot. It worked. Have a nice day.
