### ISSUE TITLE
Images not sizing correctly in landing page blog summary

### ISSUE THREAD

**Issue by Galacycy** [opera7133/tella#112]
Hi- I'm new to creating my own website, including using Hugo but making good progress with your clean and simple theme. Thank you.

Issue: My blog images are not sizing correctly on a large monitor. I tried limiting the width but then I lose image aspect ratio and it looks distorted.

Specifics: My blog images are defined in each blog's markdown front matter and stored in my site's static/img directory. Is there a way to have any size jpg resized automatically to fit the the summary container with apect ratio preserved or do I have to use the same aspect ratio for every jpg I use to maintain consistency? Or maybe the solution is elsewhere?
![Screenshot at 2022-08-23 13-14-41](https://user-images.githubusercontent.com/111723274/186258531-e9bbc56a-65ec-4386-87d3-667df7b28d66.png)

**Comment by opera7133** [comment]
With the commit of e8d2f86, the image ratio is now fixed at 16:9.
If it doesn't look very nice, or if it is not what you expected, please let me know.
