### ISSUE TITLE
Preventing loading Google Fonts - using local fonts

### ISSUE THREAD

**Issue by jschwarzkopf** [opera7133/tella#113]
Dear all

due to legal relevance (DSGVO in Europe) I'd like to prevent loading Google Fonts from Google. As far as I understand this is possible and done this wonderful theme so far. (e.g. icomoon; fa-...)

But how to use the Montserrat font locally? Downloading an copying the files into the local /fonts/ folder and changing the custom.css doesn't seem to work.

An [online check](https://sicher3.de/google-fonts-checker/) resulted in the usage of one Google font online. The full-text search found a link only in /layouts/partials/footer.html line No. 39 . Deleting this line or leaving all blank between " " works without errors but the look of the site suffers then.

Is it really correct to edit the footer.html file? It also seems that 'Montserrat' font is part of the local stored icomoon anyway? How to prevent any load of Google fonts?

Thank you.

**Comment by opera7133** [comment]
Added googleFonts option to config. Disabling it will load fonts from local. 
However, Thin, Light, SemiBold, ExtraBold, and Black fonts are not available. (We will add this option if requested.)

**Comment by jschwarzkopf** [comment]
Thanks a lot. This is fine for me.
