### ISSUE TITLE
Two different versions of tailwind called out in assets/css/style.css

### ISSUE THREAD

**Issue by Galacycy** [opera7133/tella#114]
> Hi Mr Wamo,
Thank you for your time. 

I am trying to understand how the style.css and custom.css files work in this theme. A few questions.

Question 1: 
Why does the "tailwindcss" version called out in the assets/css/style.css file change after npm run? 
Directly after downloading your theme, I see the following:

![Screenshot at 2022-09-03 17-48-43](https://user-images.githubusercontent.com/111723274/188297550-9621e558-2c3f-4307-9d89-f9a3b37281ab.png)

After I do npm run (and also npm run build) the version in the assets/css/style.css changes to:

![Screenshot at 2022-09-03 17-47-20](https://user-images.githubusercontent.com/111723274/188297604-8ceb77bd-6832-4414-95b7-f632a69407bc.png)

These files are not exactly the same and I don't understand what is happening here.

I am new to this so forgive my ingnorance.

Thank you for your time.

**Comment by opera7133** [comment]
style.css is a CSS file generated by tailwind based on main.css.
Each time you preview or build, style.css is updated.
If the environment you are using has the latest tailwind, the version will change.
