### ISSUE TITLE
How to customize the style.css files

### ISSUE THREAD

**Issue by Galacycy** [opera7133/tella#115]
Hello again
Question 2: What do you recommend as the best practice for customizing any of the css files?

Specifically the style.css files:

themes/tella/asssets/css/style.css

themes/tella/static/css/style.css (and/or the style.min.css)

**Comment by opera7133** [comment]
You can override or add tailwind styles by adding them to main.css like [this](https://tailwindcss.com/docs/adding-custom-styles#using-css-and-layer).
You can also override all styles by using `static/css/custom.css`.

**Comment by opera7133** [comment]
Yes, the style written in main.css has first priority.
`main.css` is once built by tailwind and generated as `style.css`.
Then (if not in preview) Hugo removes unused class names in `style.css` and outputs minified CSS.
That is what is actually used.
