### ISSUE TITLE
Bold not working

### ISSUE THREAD

**Issue by Dominic-Wagner** [opera7133/tella#60]
Bold is not working on https://tella.pages.dev/blog/markdown-syntax/
and also not on my local installation.

**Comment by opera7133** [comment]
Apparently, the strong tag in Tailwind has ```font-weight: bolder``` applied to it. However, there is nothing in Open Sans that matches Bolder, which is probably why.
I will fix it soon.

**Comment by opera7133** [comment]
The font-weight is now set to 700 in [this commit](https://github.com/opera7133/tella/commit/332b15e6db44279e1a63a1c62da2b8419e88da47).
Please check it in your environment to make sure.

**Comment by Dominic-Wagner** [comment]
Thank you.
It's working now.
