### ISSUE TITLE
Logo size adjustment

### ISSUE THREAD

**Issue by pale-bluedot** [opera7133/tella#78]
My logo png file is 659x659. However, it displays quite small on the site.

Is there a way to size the img under [params.logo]?

Thank you.

**Comment by pale-bluedot** [comment]
I appreciate this!

I just tried it but it seems only `h-14` and` h-10` work. `h-14` leaves it at the default size and `h-10` makes it a bit smaller. Any other value makes my logo huge like this. I'm using a .png file format if that makes any difference.

![logo-big](https://user-images.githubusercontent.com/72536144/149843000-d1fb84bf-c522-438a-b65b-b0586b64654c.png)

**Comment by opera7133** [comment]
It seems that the Tailwind CSS classes are not being applied correctly.
If you have specified the wrong class name, please see [here](https://tailwindcss.com/docs/height).
If you have specified it correctly, please try this :
* Delete the `resources` folder.
* Add `config.toml` to the `content` of `tailwind.config.js`.

**Comment by pale-bluedot** [comment]
I've tried many class values and they all size it to the kind shown in my previous post. Except for `h-14` which keeps it at the size prior to this open issue.

I deleted the `resources` folder and rebuilt. The `tailwind.config.js` looks good:

```
module.exports = {
  content: ["./**/*.html", "./config.toml"],
  theme: {
    extend: {
      colors: {
        tlgray: {
          200: "#E5E7EB",
          400: "#9CA3AF",
          700: "#374151",
          800: "#1F2937"
        }
      }
    }
  },
  variants: {},
  plugins: [require("@tailwindcss/typography")],
};
```

**Comment by opera7133** [comment]
Unfortunately, I don't know the cause of the problem, as it works fine in my environment.
However, by using `custom.css`, you can specify the CSS without changing the theme.
Try entering the appropriate class name in the `size` parameter and add the appropriate style to `custom.css`.
