### ISSUE TITLE
Failed to build site under Hugo 0.92.1

### ISSUE THREAD

**Issue by royqh1979** [opera7133/tella#87]
When I'm trying to build hugo site with tella as the default theme, I got the following error message:

`e:\workspace\contributes\redpandacpp>hugo server
Start building sites …
hugo v0.92.1-85E2E862 windows/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): (node:3424) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:698:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
Built in 1765 ms`

What should I do?

**Comment by opera7133** [comment]
Please upgrade Node.js to version 16 or later.

**Comment by royqh1979** [comment]
thanks!

**Comment by royqh1979** [comment]
btw, it seems that there's some error in the package.json：
‘
  "scripts": {
    "start": "concurrently npm:watch:*",
    "watch:tw": "tailwindcss -i ./themes/tella/assets/css/main.css -o ./themes/tella/assets/css/style.css --watch",
    "watch:hugo": "hugo server",
    "build": "tailwindcss -i ./themes/Blonde/assets/css/main.css -o ./themes/Blonde/assets/css/style.css && hugo --minify"
  },
’
in "build", it should be "themes/tella" instead of "themes/Blonede"?

**Comment by opera7133** [comment]
OK I forgot change that text.
Thanks.
