### ISSUE TITLE
Checklist Rendering

### ISSUE THREAD

**Issue by sylvrs** [opera7133/tella#91]
As of the current commit, checklists are not being rendered as they should: 
![image](https://user-images.githubusercontent.com/13668008/153734991-10f0a9d0-4978-42b5-bb3f-9154b5943034.png)

Here is what I had in the markdown file:
```
  - [x] Grievance Officer
  - [x] Secretary
  ```
As I do not believe this to be a Hugo issue (given that they added support for checklists some time ago), I opted to report it here. Could this be a user configuration issue or is there something larger at hand?

Any help is appreciated! :)

**Comment by opera7133** [comment]
In the tella theme, I had disabled `-webkit-appearance` to make the form display more visible from mobile browsers. This seemed to give problems with the display of checkboxes, so we enabled it for checkboxes only.
Please try to see if it displays properly!

**Comment by sylvrs** [comment]
That was definitely an improvement! Checked boxes work now, but I'm unable to get the style working for unchecked boxes. Furthermore, the list style is still showing up next to the checkbox. I'll look into the issue and see if I can maybe make a PR for this (if you don't already have it fixed by the time I create one).
![image](https://user-images.githubusercontent.com/13668008/153741919-6b089059-ae4b-48ab-8568-e560bf07c0d4.png)

**Comment by opera7133** [comment]
I had applied the style only to checked, so I fixed that.
However, I couldn't think of a way to disable the list style for checkboxes, since `:has` is not yet supported by the major browsers and goldmark doesn't add a class to the parent element of a checkbox.

**Comment by opera7133** [comment]
This is a bit of a forced solution, but you can use a shortcode to hide the list style now.
Use it like this.
```markdown
{{< begin-task-list >}}
  - [x] Grievance Officer
  - [x] Secretary
```

**Comment by sylvrs** [comment]
That definitely seems like a good solution for now. Once `:has` is supported, it'll be a lot easier though. Thank you for such a hasty fix on these issues!
