### ISSUE TITLE
features.json - link external tab and image

### ISSUE THREAD

**Issue by pale-bluedot** [opera7133/tella#99]
Hi,

I wasn't sure if to create two separate issues (please let me know).

1) Is there a way for the link to function as a new tab when it's clicked on?
2) Can I use an image instead of the Font Awesome icons?

Thanks in advance!

**Comment by opera7133** [comment]
Unfortunately, neither of those two functions are made.
The former will be created soon.
The latter will be a while later, as I need to change the json structure a bit.

**Comment by pale-bluedot** [comment]
Sounds good! I will close this for now. Please let us know of any updates.
